/* constants.js — all shared data tables & tuning constants. Lead-owned; read-only contract. */

window.TC = window.TC || {};

TC.VERSION = "0.1.0";

TC.CONST = {
  TS: 16,
  ZOOM: 2,
  WORLD_W: 1200,
  WORLD_H: 400,

  // player physics (px/s unless noted)
  GRAVITY: 1500,
  MAX_FALL: 900,
  JUMP_VEL: 430,
  COYOTE: 0.08,
  RUN_ACCEL: 1500,
  RUN_MAX: 185,
  GROUND_FRICTION: 1800,
  AIR_FRICTION: 250,
  SWIM_GRAVITY_MULT: 0.35,
  SWIM_MAX_FALL: 130,
  SWIM_STROKE: -150,
  SWIM_MOVE_MULT: 0.7,

  PLAYER_W: 18,
  PLAYER_H: 40,
  PLAYER_HP: 100,
  REACH: 88, // interaction distance in px (~5.5 tiles)
  IFRAMES: 0.7,
  CRIT_CHANCE: 0.08,
  DMG_VARIANCE: 0.12,
  REGEN_DELAY: 9,
  REGEN_RATE: 1.6, // seconds of no damage before regen; hp/s
  FALL_SAFE_TILES: 22,
  FALL_DMG_PER_TILE: 6,
  RESPAWN_SECONDS: 5,
  LAVA_TICK: 0.5,
  LAVA_DMG: 25, // seconds between burns; damage per burn
  BREATH_SECONDS: 10,
  DROWN_DMG: 15, // air supply underwater; damage per second after

  DAY_LENGTH: 420,
  NIGHT_LENGTH: 240, // seconds

  PICKUP_PULL: 44,
  PICKUP_COLLECT: 16,
  DROP_LIFETIME: 300,

  MAX_ENEMIES: 8,
  ENEMY_MIN_DIST: 26,
  ENEMY_MAX_DIST: 44,
  ENEMY_DESPAWN_DIST: 90, // tiles
  ENEMY_TOUCH_COOLDOWN: 0.8,
  MAX_BOSSES: 1,
  EQUIP_SLOTS: ["head", "body", "feet"],

  AUTOSAVE_INTERVAL: 30,

  LIGHT: {
    skyDay: 1.0,
    skyNight: 0.14,
    decayAir: 0.075,
    decaySolid: 0.28,
    interval: 0.08,
    margin: 14,
  },
  LIGHT_QUALITY: "high", // 'low' halves the overlay resolution for cheap GPUs

  GEN: {
    baseSurface: 110,
    surfaceAmplitude: 22,
    surfaceFreq: 0.006,
    dirtDepthMin: 16,
    dirtDepthVar: 16,
    desertCount: 2,
    desertWidthMin: 50,
    desertWidthVar: 70,
    caveFreq: 0.05,
    caveThreshold: 0.34,
    caveStartDepth: 12,
    worms: 110,
    wormLenMin: 30,
    wormLenVar: 90,
    wormRadMin: 1.4,
    wormRadVar: 1.8,
    ores: {
      copper: { veins: 240, sizeMin: 4, sizeVar: 6, minYOff: 6, maxYOff: 999 },
      iron: { veins: 170, sizeMin: 3, sizeVar: 5, minYOff: 35, maxYOff: 999 },
      gold: { veins: 95, sizeMin: 3, sizeVar: 4, minYAbs: 235, maxYAbs: 395 },
    },
    trees: {
      minSpacing: 5,
      varSpacing: 9,
      hMin: 6,
      hVar: 7,
      leafRadMin: 2,
      leafRadVar: 1,
    },
    tallGrassChance: 0.32,
    flowerChance: 0.07,
    waterPools: 26,
    waterMinY: 255,
    waterMaxTiles: 220,
    bedrockRows: 2,
    biomes: {
      snowCount: 1,
      snowWidthMin: 60,
      snowWidthVar: 80,
      jungleCount: 1,
      jungleWidthMin: 70,
      jungleWidthVar: 90,
    },
    underworld: {
      startY: 355,
      cavernFreq: 0.04,
      cavernThreshold: 0.22,
      lavaPools: 40,
      lavaMaxTiles: 300,
    },
  },

  SPAWN: {
    day: [
      ["green_slime", 3],
      ["blue_slime", 1],
    ],
    night: [
      ["zombie", 3],
      ["demon_eye", 2],
    ],
    cave: [
      ["blue_slime", 4],
      ["cave_bat", 2],
    ],
    attemptDay: 5.5,
    attemptNight: 1.1,
    attemptCave: 3.0,
    attemptUnderworld: 2.2,
  },

  COLORS: {
    dealt: "#ffb066",
    crit: "#ff5a48",
    taken: "#ff4a4a",
    heal: "#7dff7d",
    copper: "#c87137",
    iron: "#c0c0cc",
    gold: "#ffd24a",
    wood: "#8a5a32",
  },

  STARTER_KIT: [
    ["copper_pickaxe", 1],
    ["copper_axe", 1],
    ["copper_sword", 1],
    ["torch", 5],
  ],
};

// ---- tile ids ----
// NOTE: ids 27..34 (CACTUS..SANDSTONE_BRICK) were historically appended by
// worldgen.js at script-load time. They were promoted here (same order, same
// numeric ids) so ALL shared content lives in this lead-owned table and no
// module mutates shared tables at load time. Never renumber or reorder these.
TC.TILE = {
  AIR: 0,
  DIRT: 1,
  GRASS: 2,
  STONE: 3,
  WOOD: 4,
  TRUNK: 5,
  LEAVES: 6,
  SAND: 7,
  COPPER_ORE: 8,
  IRON_ORE: 9,
  GOLD_ORE: 10,
  BEDROCK: 11,
  TORCH: 12,
  WORKBENCH: 13,
  FURNACE: 14,
  ANVIL: 15,
  TALLGRASS: 16,
  FLOWER_RED: 17,
  FLOWER_YELLOW: 18,
  WATER: 19,
  GLASS: 20,
  CHEST: 21,
  DOOR_CLOSED: 22,
  DOOR_OPEN: 23,
  SNOW: 24,
  JGRASS: 25,
  LAVA: 26,
  CACTUS: 27,
  EBONSTONE: 28,
  CRIMSTONE: 29,
  EBONGRASS: 30,
  SHADEWOOD: 31,
  DUNGEON_BRICK: 32,
  HELL_BRICK: 33,
  SANDSTONE_BRICK: 34,
  // W4 campaign: micro-biome blocks + expanded ore tiers (append-only).
  GLEAM: 35,
  MUSHGRASS: 36,
  MUSHSTEM: 37,
  GRANITE: 38,
  MARBLE: 39,
  MOSSSTONE: 40,
  SILVER_ORE: 41,
  CRYSTAL_ORE: 42,
};

// def fields: solid, opaque(blocks light), hardness(sec to mine at 100 power), tool
// ('pick'|'axe'|'any'), minPower, drop(item id or null), light(0..1 emission),
// pattern(drives TC.Tiles.drawTile), needsSupport('below'|'any'|null),
// replaceable(can be overwritten by placement), colors[]
function D(name, o) {
  return Object.assign(
    {
      name,
      solid: false,
      opaque: false,
      hardness: 0,
      tool: null,
      minPower: 0,
      drop: null,
      light: 0,
      pattern: "empty",
      needsSupport: null,
      replaceable: false,
    },
    o,
  );
}

TC.TILE_DEFS = [
  /* AIR           */ D("air", {}),
  /* DIRT          */ D("dirt", {
    solid: true,
    opaque: true,
    hardness: 0.25,
    tool: "pick",
    drop: "dirt",
    pattern: "speckle",
    colors: ["#8a5a32", "#7a4e2b", "#96653a"],
  }),
  /* GRASS         */ D("grass", {
    solid: true,
    opaque: true,
    hardness: 0.3,
    tool: "pick",
    drop: "dirt",
    pattern: "grass",
    colors: ["#8a5a32", "#3fae49"],
  }),
  /* STONE         */ D("stone", {
    solid: true,
    opaque: true,
    hardness: 0.5,
    tool: "pick",
    drop: "stone",
    pattern: "speckle",
    colors: ["#7d7d7d", "#6d6d6d", "#8d8d8d"],
  }),
  /* WOOD          */ D("wood block", {
    solid: true,
    opaque: true,
    hardness: 0.35,
    tool: "any",
    drop: "wood",
    pattern: "plank",
    colors: ["#a97d4b", "#96703f"],
  }),
  /* TRUNK         */ D("tree", {
    hardness: 0.6,
    tool: "axe",
    drop: "wood",
    pattern: "trunk",
    colors: ["#7a5230", "#6a4628"],
  }),
  /* LEAVES        */ D("leaves", {
    hardness: 0.1,
    tool: "any",
    drop: null,
    pattern: "leafy",
    colors: ["#2f8f38", "#27762f", "#38a042"],
  }),
  /* SAND          */ D("sand", {
    solid: true,
    opaque: true,
    hardness: 0.25,
    tool: "pick",
    drop: "sand",
    pattern: "speckle",
    colors: ["#d8c86e", "#cbbd60", "#e2d47c"],
  }),
  /* COPPER_ORE    */ D("copper ore", {
    solid: true,
    opaque: true,
    hardness: 0.75,
    tool: "pick",
    drop: "copper_ore",
    pattern: "ore",
    colors: ["#7d7d7d", "#c87137"],
  }),
  /* IRON_ORE      */ D("iron ore", {
    solid: true,
    opaque: true,
    hardness: 0.85,
    tool: "pick",
    drop: "iron_ore",
    pattern: "ore",
    colors: ["#7d7d7d", "#c0c0cc"],
  }),
  /* GOLD_ORE      */ D("gold ore", {
    solid: true,
    opaque: true,
    hardness: 0.95,
    tool: "pick",
    drop: "gold_ore",
    pattern: "ore",
    colors: ["#7d7d7d", "#ffd24a"],
  }),
  /* BEDROCK       */ D("bedrock", {
    solid: true,
    opaque: true,
    hardness: 9999,
    minPower: 9999,
    drop: null,
    pattern: "speckle",
    colors: ["#2e2e34", "#26262b"],
  }),
  /* TORCH         */ D("torch", {
    hardness: 0.05,
    tool: "any",
    drop: "torch",
    light: 1.0,
    pattern: "torch",
    needsSupport: "any",
    colors: ["#8a6a3a", "#ffd76a"],
  }),
  /* WORKBENCH     */ D("workbench", {
    solid: true,
    opaque: false,
    hardness: 0.3,
    tool: "any",
    drop: "workbench",
    pattern: "workbench",
    needsSupport: "below",
    colors: ["#a97d4b", "#7a5230"],
  }),
  /* FURNACE       */ D("furnace", {
    solid: true,
    opaque: false,
    hardness: 0.4,
    tool: "any",
    drop: "furnace",
    pattern: "furnace",
    needsSupport: "below",
    light: 0.55,
    colors: ["#6d6d6d", "#3d3d3d", "#ff8c3a"],
  }),
  /* ANVIL         */ D("anvil", {
    solid: true,
    opaque: false,
    hardness: 0.4,
    tool: "any",
    drop: "anvil",
    pattern: "anvil",
    needsSupport: "below",
    colors: ["#4a4a52", "#6a6a74"],
  }),
  /* TALLGRASS     */ D("tall grass", {
    hardness: 0.01,
    tool: "any",
    drop: null,
    pattern: "plant",
    needsSupport: "below",
    replaceable: true,
    colors: ["#3fae49"],
  }),
  /* FLOWER_RED    */ D("red bloom", {
    hardness: 0.01,
    tool: "any",
    drop: null,
    pattern: "plant",
    needsSupport: "below",
    replaceable: true,
    colors: ["#3fae49", "#d84a4a"],
  }),
  /* FLOWER_YELLOW */ D("yellow bloom", {
    hardness: 0.01,
    tool: "any",
    drop: null,
    pattern: "plant",
    needsSupport: "below",
    replaceable: true,
    colors: ["#3fae49", "#e8d24a"],
  }),
  /* WATER         */ D("water", {
    hardness: 9999,
    minPower: 9999,
    drop: null,
    pattern: "liquid",
    replaceable: true,
    colors: ["#3a6ea8", "#5a8ec8"],
  }),
  /* GLASS         */ D("glass", {
    solid: true,
    opaque: false,
    hardness: 0.2,
    tool: "pick",
    drop: "glass",
    pattern: "glass",
    colors: ["#bcd9e8"],
  }),
  /* CHEST         */ D("chest", {
    solid: true,
    opaque: false,
    hardness: 0.35,
    tool: "any",
    drop: "chest",
    pattern: "chest",
    needsSupport: "below",
    colors: ["#8a5a32", "#ffd24a"],
  }),
  /* DOOR_CLOSED   */ D("door", {
    solid: true,
    opaque: false,
    hardness: 0.25,
    tool: "any",
    drop: "door",
    pattern: "door",
    needsSupport: "below",
    colors: ["#a97d4b", "#7a5230"],
  }),
  /* DOOR_OPEN     */ D("door (open)", {
    hardness: 0.25,
    tool: "any",
    drop: "door",
    pattern: "door_open",
    needsSupport: "below",
    colors: ["#a97d4b", "#7a5230"],
  }),
  /* SNOW          */ D("snow", {
    solid: true,
    opaque: true,
    hardness: 0.2,
    tool: "pick",
    drop: "snow",
    pattern: "speckle",
    colors: ["#e8f0f4", "#d8e4ec", "#f4f8fa"],
  }),
  /* JGRASS        */ D("jungle grass", {
    solid: true,
    opaque: true,
    hardness: 0.3,
    tool: "pick",
    drop: "dirt",
    pattern: "grass",
    colors: ["#8a5a32", "#2f9e3f"],
  }),
  /* LAVA          */ D("lava", {
    hardness: 9999,
    minPower: 9999,
    drop: null,
    pattern: "liquid",
    replaceable: true,
    light: 0.9,
    colors: ["#e85a1a", "#ffb03a"],
  }),
  /* CACTUS (ex-worldgen extension, promoted verbatim) */
  /* CACTUS        */ D("cactus", {
    hardness: 0.3,
    tool: "any",
    drop: "cactus",
    pattern: "leafy",
    needsSupport: "below",
    colors: ["#3f8f43", "#35793a", "#4da04f"],
  }),
  /* EBONSTONE     */ D("ebonstone", {
    solid: true,
    opaque: true,
    hardness: 0.6,
    tool: "pick",
    drop: "ebonstone",
    pattern: "speckle",
    colors: ["#565064", "#484254", "#645e72"],
  }),
  /* CRIMSTONE     */ D("crimstone", {
    solid: true,
    opaque: true,
    hardness: 0.6,
    tool: "pick",
    drop: "crimstone",
    pattern: "speckle",
    colors: ["#6e4646", "#5e3a3a", "#7e5252"],
  }),
  /* EBONGRASS     */ D("corrupt grass", {
    solid: true,
    opaque: true,
    hardness: 0.3,
    tool: "pick",
    drop: "dirt",
    pattern: "grass",
    colors: ["#4e4254", "#8a5cba"],
  }),
  /* SHADEWOOD     */ D("shadewood", {
    solid: true,
    opaque: true,
    hardness: 0.35,
    tool: "any",
    drop: "shadewood",
    pattern: "plank",
    colors: ["#4a3550", "#372740"],
  }),
  /* DUNGEON_BRICK */ D("dungeon brick", {
    solid: true,
    opaque: true,
    hardness: 0.55,
    tool: "pick",
    drop: "dungeon_brick",
    pattern: "plank",
    colors: ["#4e5f7d", "#3c4a63"],
  }),
  /* HELL_BRICK    */ D("hell brick", {
    solid: true,
    opaque: true,
    hardness: 0.55,
    tool: "pick",
    drop: "hell_brick",
    pattern: "plank",
    colors: ["#66302a", "#4e241f"],
  }),
  /* SANDSTONE_BRICK */ D("sandstone brick", {
    solid: true,
    opaque: true,
    hardness: 0.4,
    tool: "pick",
    drop: "sandstone_brick",
    pattern: "plank",
    colors: ["#c9ae6e", "#ad9257"],
  }),
  /* W4 campaign: deep-cavern micro-biome blocks + expanded ore tiers.
     New ids append only; never renumber. Patterns reuse existing painters
     so tiles.js renders them without modification. */
  /* GLEAM         */ D("gleamstone", {
    solid: true,
    opaque: true,
    hardness: 0.55,
    tool: "pick",
    drop: "gleam",
    pattern: "speckle",
    light: 0.4,
    colors: ["#3d7a78", "#57b8b2", "#7fe0d8"],
  }),
  /* MUSHGRASS     */ D("mushroom grass", {
    solid: true,
    opaque: true,
    hardness: 0.3,
    tool: "pick",
    drop: "mushgrass",
    pattern: "grass",
    colors: ["#5a4468", "#9a6ac8"],
  }),
  /* MUSHSTEM      */ D("mushroom stem", {
    solid: true,
    opaque: false,
    hardness: 0.25,
    tool: "any",
    drop: "mushstem",
    pattern: "plank",
    colors: ["#d8ccb8", "#bfb098"],
  }),
  /* GRANITE       */ D("granite", {
    solid: true,
    opaque: true,
    hardness: 0.65,
    tool: "pick",
    drop: "granite",
    pattern: "speckle",
    colors: ["#4a4258", "#3a3448", "#5a5268"],
  }),
  /* MARBLE        */ D("marble", {
    solid: true,
    opaque: true,
    hardness: 0.6,
    tool: "pick",
    drop: "marble",
    pattern: "speckle",
    colors: ["#d8d2c8", "#c4beb4", "#e8e2da"],
  }),
  /* MOSSSTONE     */ D("mossy stone", {
    solid: true,
    opaque: true,
    hardness: 0.5,
    tool: "pick",
    drop: "moss_stone",
    pattern: "speckle",
    colors: ["#5d6b52", "#4a5842", "#6e7c62"],
  }),
  /* SILVER_ORE    */ D("silver ore", {
    solid: true,
    opaque: true,
    hardness: 0.9,
    tool: "pick",
    minPower: 55,
    drop: "silver_ore",
    pattern: "ore",
    colors: ["#7d7d7d", "#d8dce8"],
  }),
  /* CRYSTAL_ORE   */ D("gleam crystal", {
    solid: true,
    opaque: true,
    hardness: 1.05,
    tool: "pick",
    minPower: 75,
    drop: "crystal",
    pattern: "ore",
    light: 0.25,
    colors: ["#3d3a52", "#b07ae8"],
  }),
];

// ---- wall ids (background layer) ----
// SAND/EBON/DUNGEON/HELL were historically appended by worldgen.js at load
// time; promoted here (same order, same numeric ids). Never renumber.
TC.WALL = {
  NONE: 0,
  DIRT: 1,
  STONE: 2,
  SAND: 3,
  EBON: 4,
  DUNGEON: 5,
  HELL: 6,
  GRANITE: 7,
  MARBLE: 8,
  MOSS: 9,
  GLEAM: 10,
};

TC.WALL_DEFS = [
  { name: "none", color: null, hardness: 0 },
  { name: "dirt wall", color: "#59402a", hardness: 0.3 },
  { name: "stone wall", color: "#464649", hardness: 0.45 },
  { name: "sand wall", color: "#b09a58", hardness: 0.25 },
  { name: "ebonstone wall", color: "#3a3444", hardness: 0.4 },
  { name: "dungeon wall", color: "#333f54", hardness: 0.45 },
  { name: "hell brick wall", color: "#401d18", hardness: 0.45 },
  // W4 campaign: micro-biome background walls (append-only)
  { name: "granite wall", color: "#342e42", hardness: 0.45 },
  { name: "marble wall", color: "#a89f92", hardness: 0.4 },
  { name: "moss wall", color: "#3c4a36", hardness: 0.35 },
  { name: "gleam wall", color: "#2c4a48", hardness: 0.4 },
];

// ---- items ----
function I(name, kind, o) {
  return Object.assign(
    {
      name,
      kind,
      maxStack:
        kind === "block" || kind === "material" || kind === "ammo" ? 999 : 1,
    },
    o,
  );
}

TC.ITEM_DEFS = {
  dirt: I("Dirt Block", "block", { tile: TC.TILE.DIRT }),
  stone: I("Stone Block", "block", { tile: TC.TILE.STONE }),
  wood: I("Wood", "block", { tile: TC.TILE.WOOD }),
  sand: I("Sand Block", "block", { tile: TC.TILE.SAND }),
  glass: I("Glass", "block", { tile: TC.TILE.GLASS }),
  torch: I("Torch", "block", { tile: TC.TILE.TORCH }),
  workbench: I("Workbench", "block", { tile: TC.TILE.WORKBENCH }),
  furnace: I("Furnace", "block", { tile: TC.TILE.FURNACE }),
  anvil: I("Anvil", "block", { tile: TC.TILE.ANVIL }),
  chest: I("Chest", "block", { tile: TC.TILE.CHEST }),
  door: I("Wooden Door", "block", { tile: TC.TILE.DOOR_CLOSED }),
  snow: I("Snow Block", "block", { tile: TC.TILE.SNOW }),
  jungle_grass: I("Jungle Grass", "block", { tile: TC.TILE.JGRASS }),
  copper_ore: I("Copper Ore", "material", {}),
  iron_ore: I("Iron Ore", "material", {}),
  silver_ore: I("Silver Ore", "material", { value: 9 }),
  gold_ore: I("Gold Ore", "material", {}),
  crystal: I("Gleam Crystal", "material", { value: 40 }),
  gleam: I("Gleamstone", "block", { tile: TC.TILE.GLEAM }),
  mushgrass: I("Mushroom Grass", "block", { tile: TC.TILE.MUSHGRASS }),
  mushstem: I("Mushroom Stem", "block", { tile: TC.TILE.MUSHSTEM }),
  granite: I("Granite", "block", { tile: TC.TILE.GRANITE, value: 2 }),
  marble: I("Marble", "block", { tile: TC.TILE.MARBLE, value: 2 }),
  moss_stone: I("Mossy Stone", "block", { tile: TC.TILE.MOSSSTONE }),
  copper_bar: I("Copper Bar", "material", {}),
  iron_bar: I("Iron Bar", "material", {}),
  silver_bar: I("Silver Bar", "material", { value: 20 }),
  gold_bar: I("Gold Bar", "material", {}),
  gel: I("Gel", "material", {}),
  arrow: I("Arrow", "ammo", { damage: 4, value: 1 }),
  void_charm: I("Void Charm", "summon", { boss: "void_eye", maxStack: 20 }),
  // W6 campaign bosses: original summons + signature materials. kind
  // 'summon' items call TC.Enemies.spawnBoss(def.boss) at night (player.js).
  storm_bell: I("Storm Bell", "summon", { boss: "storm_jelly", maxStack: 20 }),
  moss_heart: I("Beating Moss Heart", "summon", {
    boss: "moss_mother",
    maxStack: 20,
  }),
  storm_core: I("Storm Core", "material", { value: 120 }),
  moss_core: I("Verdant Core", "material", { value: 150 }),
  // Canonical currency (TC.Economy): face value in copper units. Prices,
  // sell values and purses all speak this single integer scale.
  coin_copper: I("Copper Coin", "currency", { value: 1, maxStack: 999 }),
  coin_silver: I("Silver Coin", "currency", { value: 100, maxStack: 999 }),
  coin_gold: I("Gold Coin", "currency", { value: 10000, maxStack: 999 }),
  // Buckets: kind 'bucket' handled by TC.Liquids.onUseHeld. bucketType uses
  // TC.Liquids.TYPE numerics (1 water, 2 lava, 3 honey) since constants load
  // before the liquids module.
  bucket: I("Empty Bucket", "bucket", { bucketEmpty: true, maxStack: 999, value: 25 }),
  bucket_water: I("Water Bucket", "bucket", { bucketType: 1, maxStack: 999 }),
  bucket_lava: I("Lava Bucket", "bucket", { bucketType: 2, maxStack: 999 }),
  bucket_honey: I("Honey Bucket", "bucket", { bucketType: 3, maxStack: 999 }),
  // Grappling hooks (kind 'grapple' -> TC.Grapple): grapple = { range px,
  // pull accel px/s^2, flight speed px/s }. A short progression ladder.
  hook_basic: I("Grappling Hook", "grapple", {
    grapple: { range: 270, pull: 540, speed: 760 },
    maxStack: 1,
  }),
  hook_gemshot: I("Gemshot Hook", "grapple", {
    grapple: { range: 400, pull: 680, speed: 900 },
    maxStack: 1,
  }),
  copper_helmet: I("Copper Helmet", "armor", { slot: "head", defense: 1 }),
  copper_mail: I("Copper Mail", "armor", { slot: "body", defense: 2 }),
  copper_boots: I("Copper Greaves", "armor", { slot: "feet", defense: 1 }),
  iron_helmet: I("Iron Helmet", "armor", { slot: "head", defense: 2 }),
  silver_helmet: I("Silver Helmet", "armor", { slot: "head", defense: 3 }),
  silver_mail: I("Silver Mail", "armor", { slot: "body", defense: 4 }),
  silver_boots: I("Silver Greaves", "armor", { slot: "feet", defense: 2 }),
  crystal_blade: I("Crystal Blade", "weapon", {
    damage: 24,
    knockback: 4,
    useTime: 0.21,
  }),
  storm_blade: I("Storm Blade", "weapon", {
    damage: 30,
    knockback: 6.5,
    useTime: 0.24,
  }),
  moss_cloak: I("Verdant Cloak", "armor", { slot: "body", defense: 5 }),
  iron_mail: I("Iron Mail", "armor", { slot: "body", defense: 3 }),
  iron_boots: I("Iron Greaves", "armor", { slot: "feet", defense: 2 }),
  gold_helmet: I("Gold Helmet", "armor", { slot: "head", defense: 3 }),
  gold_mail: I("Gold Mail", "armor", { slot: "body", defense: 4 }),
  gold_boots: I("Gold Greaves", "armor", { slot: "feet", defense: 3 }),
  wooden_sword: I("Wooden Sword", "weapon", {
    damage: 7,
    knockback: 4.5,
    useTime: 0.38,
  }),
  copper_sword: I("Copper Sword", "weapon", {
    damage: 10,
    knockback: 5,
    useTime: 0.34,
  }),
  iron_sword: I("Iron Sword", "weapon", {
    damage: 15,
    knockback: 5.5,
    useTime: 0.3,
  }),
  silver_sword: I("Silver Sword", "weapon", {
    damage: 17,
    knockback: 5,
    useTime: 0.27,
  }),
  gold_sword: I("Gold Sword", "weapon", {
    damage: 19,
    knockback: 6,
    useTime: 0.26,
  }),
  copper_pickaxe: I("Copper Pickaxe", "tool", {
    tool: "pick",
    power: 35,
    useTime: 0.32,
    damage: 4,
    knockback: 2,
  }),
  iron_pickaxe: I("Iron Pickaxe", "tool", {
    tool: "pick",
    power: 55,
    useTime: 0.28,
    damage: 5,
    knockback: 2,
  }),
  silver_pickaxe: I("Silver Pickaxe", "tool", {
    tool: "pick",
    power: 65,
    useTime: 0.26,
    damage: 5,
    knockback: 2,
  }),
  gold_pickaxe: I("Gold Pickaxe", "tool", {
    tool: "pick",
    power: 75,
    useTime: 0.24,
    damage: 6,
    knockback: 2,
  }),
  copper_axe: I("Copper Axe", "tool", {
    tool: "axe",
    power: 35,
    useTime: 0.38,
    damage: 5,
    knockback: 2.5,
  }),
  iron_axe: I("Iron Axe", "tool", {
    tool: "axe",
    power: 55,
    useTime: 0.34,
    damage: 7,
    knockback: 3,
  }),
  gold_axe: I("Gold Axe", "tool", {
    tool: "axe",
    power: 75,
    useTime: 0.3,
    damage: 9,
    knockback: 3.5,
  }),
  wooden_bow: I("Wooden Bow", "ranged", {
    damage: 6,
    useTime: 0.8,
    projectile: "arrow",
  }),

  // -- ex-worldgen extension block items (promoted verbatim; ids unchanged) --
  cactus: I("Cactus", "block", { tile: TC.TILE.CACTUS }),
  ebonstone: I("Ebonstone Block", "block", { tile: TC.TILE.EBONSTONE }),
  crimstone: I("Crimstone Block", "block", { tile: TC.TILE.CRIMSTONE }),
  shadewood: I("Shadewood Block", "block", { tile: TC.TILE.SHADEWOOD }),
  dungeon_brick: I("Dungeon Brick", "block", { tile: TC.TILE.DUNGEON_BRICK }),
  hell_brick: I("Hell Brick", "block", { tile: TC.TILE.HELL_BRICK }),
  sandstone_brick: I("Sandstone Brick", "block", {
    tile: TC.TILE.SANDSTONE_BRICK,
  }),
};

// ---- crafting recipes ----
TC.RECIPES = [
  { out: "workbench", n: 1, station: null, cost: { wood: 10 } },
  { out: "torch", n: 3, station: null, cost: { wood: 1, gel: 1 } },
  { out: "wooden_sword", n: 1, station: "workbench", cost: { wood: 7 } },
  { out: "wooden_bow", n: 1, station: "workbench", cost: { wood: 10 } },
  { out: "arrow", n: 3, station: "workbench", cost: { wood: 1, stone: 1 } },
  {
    out: "furnace",
    n: 1,
    station: "workbench",
    cost: { stone: 20, wood: 4, torch: 3 },
  },
  { out: "anvil", n: 1, station: "workbench", cost: { iron_bar: 5 } },
  { out: "copper_bar", n: 1, station: "furnace", cost: { copper_ore: 3 } },
  { out: "iron_bar", n: 1, station: "furnace", cost: { iron_ore: 3 } },
  { out: "silver_bar", n: 1, station: "furnace", cost: { silver_ore: 4 } },
  { out: "gold_bar", n: 1, station: "furnace", cost: { gold_ore: 4 } },
  { out: "glass", n: 1, station: "furnace", cost: { sand: 2 } },
  {
    out: "iron_pickaxe",
    n: 1,
    station: "anvil",
    cost: { iron_bar: 10, wood: 3 },
  },
  { out: "iron_sword", n: 1, station: "anvil", cost: { iron_bar: 8 } },
  { out: "iron_axe", n: 1, station: "anvil", cost: { iron_bar: 9 } },
  {
    out: "gold_pickaxe",
    n: 1,
    station: "anvil",
    cost: { gold_bar: 10, wood: 3 },
  },
  { out: "gold_sword", n: 1, station: "anvil", cost: { gold_bar: 8 } },
  { out: "gold_axe", n: 1, station: "anvil", cost: { gold_bar: 9 } },
  { out: "copper_helmet", n: 1, station: "anvil", cost: { copper_bar: 8 } },
  { out: "copper_mail", n: 1, station: "anvil", cost: { copper_bar: 12 } },
  { out: "copper_boots", n: 1, station: "anvil", cost: { copper_bar: 6 } },
  { out: "iron_helmet", n: 1, station: "anvil", cost: { iron_bar: 8 } },
  { out: "iron_mail", n: 1, station: "anvil", cost: { iron_bar: 12 } },
  { out: "iron_boots", n: 1, station: "anvil", cost: { iron_bar: 6 } },
  { out: "gold_helmet", n: 1, station: "anvil", cost: { gold_bar: 8 } },
  { out: "gold_mail", n: 1, station: "anvil", cost: { gold_bar: 12 } },
  { out: "gold_boots", n: 1, station: "anvil", cost: { gold_bar: 6 } },
  { out: "void_charm", n: 1, station: "anvil", cost: { gel: 15, gold_bar: 3 } },
  { out: "chest", n: 1, station: "workbench", cost: { wood: 8, iron_bar: 2 } },
  { out: "door", n: 1, station: "workbench", cost: { wood: 6 } },
  { out: "bucket", n: 1, station: "anvil", cost: { iron_bar: 3 } },
  { out: "hook_basic", n: 1, station: "anvil", cost: { iron_bar: 10, wood: 5 } },
  {
    out: "hook_gemshot",
    n: 1,
    station: "anvil",
    cost: { gold_bar: 8, glass: 12 },
  },
  // silver tier (W4/W5 progression): between iron and gold
  { out: "silver_sword", n: 1, station: "anvil", cost: { silver_bar: 8 } },
  {
    out: "silver_pickaxe",
    n: 1,
    station: "anvil",
    cost: { silver_bar: 10, wood: 3 },
  },
  { out: "silver_helmet", n: 1, station: "anvil", cost: { silver_bar: 8 } },
  { out: "silver_mail", n: 1, station: "anvil", cost: { silver_bar: 12 } },
  { out: "silver_boots", n: 1, station: "anvil", cost: { silver_bar: 6 } },
  // gleam crystal gear (deep-cavern endgame pre-hardmode)
  {
    out: "crystal_blade",
    n: 1,
    station: "anvil",
    cost: { crystal: 6, silver_bar: 6 },
  },
  // W6 boss summons + boss-craft gear
  {
    out: "storm_bell",
    n: 1,
    station: "anvil",
    cost: { iron_bar: 5, gel: 12 },
  },
  {
    out: "moss_heart",
    n: 1,
    station: "workbench",
    cost: { mushgrass: 20, jungle_grass: 5 },
  },
  // W14: post-boss crafts declare their progression gates with the shared
  // condition grammar (TC.Progression.test) instead of implicit drops-only
  // gating — the UI can now explain WHY a recipe is locked.
  { out: "storm_blade", n: 1, station: "anvil",
    requires: "boss.storm_jelly.defeated",
    cost: { storm_core: 8, silver_bar: 10 } },
  { out: "moss_cloak", n: 1, station: "workbench",
    requires: "boss.moss_mother.defeated",
    cost: { moss_core: 6, mushstem: 25 } },
];

// ---- economy: base item values (copper units; TC.Economy scale) ----
// Shop buy prices may override per stock entry; this table is the fallback
// and the sell anchor (sell = max(1, floor(value/5))). Items absent here
// have no base value and cannot be sold to shopkeepers.
(function () {
  const V = {
    dirt: 0, stone: 1, wood: 1, sand: 1, snow: 1, glass: 4,
    torch: 2, workbench: 3, furnace: 12, anvil: 20, chest: 15, door: 8,
    gel: 1,
    copper_ore: 3, iron_ore: 6, gold_ore: 15,
    silver_ore: 9, crystal: 40,
    gleam: 3, mushgrass: 1, mushstem: 1, moss_stone: 1,
    copper_bar: 5, iron_bar: 12, gold_bar: 30, silver_bar: 20,
    wooden_sword: 4,
    copper_sword: 50, iron_sword: 120, gold_sword: 250,
    copper_pickaxe: 60, iron_pickaxe: 150, gold_pickaxe: 300,
    copper_axe: 55, iron_axe: 140, gold_axe: 280,
    wooden_bow: 30,
    copper_helmet: 40, copper_mail: 60, copper_boots: 30,
    iron_helmet: 90, iron_mail: 140, iron_boots: 70,
    silver_sword: 170, silver_pickaxe: 200, crystal_blade: 600,
    silver_helmet: 130, silver_mail: 210, silver_boots: 100,
    storm_core: 30, moss_core: 38,
    storm_blade: 900, moss_cloak: 850,
    gold_helmet: 180, gold_mail: 280, gold_boots: 140,
    void_charm: 500,
    bucket_water: 30, bucket_lava: 60, bucket_honey: 45,
    hook_basic: 120, hook_gemshot: 400,
  };
  for (const id in V) {
    if (TC.ITEM_DEFS[id]) TC.ITEM_DEFS[id].value = V[id];
  }
})();

// ---- enemies ----
// coins: [minCopper, maxCopper] dropped on death (TC.Economy.dropCoins).
TC.ENEMY_DEFS = {
  green_slime: {
    name: "Green Slime",
    hp: 14,
    dmg: 12,
    kbResist: 0.2,
    ai: "slime",
    w: 26,
    h: 18,
    color: "#3ec54a",
    coins: [0, 2],
    drops: [{ id: "gel", min: 1, max: 2, chance: 1 }],
  },
  blue_slime: {
    name: "Blue Slime",
    hp: 25,
    dmg: 14,
    kbResist: 0.35,
    ai: "slime",
    w: 34,
    h: 22,
    color: "#4a6fd6",
    coins: [4, 12],
    drops: [{ id: "gel", min: 1, max: 3, chance: 1 }],
  },
  zombie: {
    name: "Zombie",
    hp: 45,
    dmg: 15,
    kbResist: 0.6,
    ai: "zombie",
    w: 22,
    h: 42,
    color: "#7a9e5a",
    coins: [15, 35],
    drops: [],
  },
  demon_eye: {
    name: "Demon Eye",
    hp: 52,
    dmg: 18,
    kbResist: 0.5,
    ai: "eye",
    w: 26,
    h: 26,
    color: "#c93a3a",
    coins: [25, 55],
    drops: [],
  },
  cave_bat: {
    name: "Cave Bat",
    hp: 16,
    dmg: 10,
    kbResist: 0.2,
    ai: "bat",
    w: 20,
    h: 16,
    color: "#6a5a4a",
    coins: [8, 18],
    drops: [],
  },
  void_eye: {
    name: "Eye of the Void",
    hp: 1200,
    dmg: 22,
    kbResist: 1,
    ai: "eye_boss",
    w: 90,
    h: 90,
    color: "#8a3ac9",
    boss: true,
    defense: 8,
    coins: [600, 1200],
    drops: [
      { id: "gel", min: 25, max: 40, chance: 1 },
      { id: "gold_bar", min: 5, max: 8, chance: 1 },
    ],
  },
};
